### ISSUE TITLE
Create file: periods.csv

### ISSUE THREAD

**Issue by afuetterer** [paneldata/pairfam#12]
### Task
- Use the the branch `data-unification` for the work.
- Please create a file according to the spec below.
- Commit with `[close #12] Create file: periods.csv`.

### Spec
filename = `periods.csv`
location = `metadata/`
headers = `study, name, label, label_de, description, description_de`

### Desired content
- all periods that are referenced in `metadata/datasets.csv`
- study: `pairfam`

**Comment by afuetterer** [comment]
Done. File passed validation.

**Comment by pairfam** [comment]
this file has since been updated.
**pull request to _paneldata/pairfam:master_ & _paneldata/pairfam:data-unification_ still open!**
