### ISSUE TITLE
Fragen zu labels und sortierung

### ISSUE THREAD

**Issue by mhebing** [paneldata/pairfam#8]
Andererseits werden manche - in den Datensätzen existente - Labels in der deutschen Version nicht angezeigt. Hier z.B. Wert 1 im deutschen: https://ddionrails.soep.de/pairfam/data/anchor1/int5 oder hier https://ddionrails.soep.de/pairfam/data/anchor8/cps5. Woran könnte das liegen?

Wäre es bei der Label Table vielleicht möglich, nach Datensatz-Typ zu sortieren? Alphabetisch (dann wären die zentralen anchor-Datensätze gleich ganz vorne)?

**Comment by afuetterer** [comment]
Can this be closed?
