### ISSUE TITLE
Create file: analysis_units.csv

### ISSUE THREAD

**Issue by afuetterer** [paneldata/pairfam#9]
### Task
- Use the the branch `data-unification` for the work.
- Please create a file according to the spec below.
- Commit with `[close #9] Create file: analysis_units.csv`.

### Spec
filename = `analysis_units.csv`
location = `metadata/`
headers = `study, name, label, label_de, description, description_de`

### Desired content
- all analysis_units that are referenced in `metadata/datasets.csv`
- study: `pairfam`

**Comment by afuetterer** [comment]
Done. File passes validation.

**Comment by pairfam** [comment]
this file has since been updated. 
**pull request to** _paneldata/pairfam:master_ **&** _paneldata/pairfam:data-unification_ **still open!**
